### ISSUE TITLE
The package is not available in a stable-enough version according to your minimum-stability setting    see

### ISSUE THREAD

**Issue by hiddenl00p** [nylas/nylas-php#1]
We tried setting our min-stability to dev. or by "nylas/nylas-php": "dev-master@dev"  but still getting below issue.
# 

Problem 1
    - The requested package nylas/nylas-php could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

**Comment by KartikTalwar** [comment]
Hey @hiddenl00p I just updated the composer.json to reflect the inconsistency in the package name. Would you mind giving it another try?

The package can now also be found at https://packagist.org/packages/nylas/nylas-php

**Comment by hiddenl00p** [comment]
Is it possible to use Guzzle 5.0 or latest? All the packages we using are on 5.0.
