### ISSUE TITLE
This PHP library is still using the old namespace endpoints that had been depreciated and will not work

### ISSUE THREAD

**Issue by harrysinghtiwana** [nylas/nylas-php#7]
This PHP library is still using the old namespace endpoints that had been depreciated and will not work: 

https://github.com/nylas/nylas-php/blob/f58a2de62f1a093cf4527471ff8237097081d4d0/src/Nylas.php#L15

**Comment by KartikTalwar** [comment]
@lawcus apologies for the lack of updates on this library. The new changes pushed to the repo are now up to date with the current API endpoints.
